using System;
using Microsoft.SqlServer.Dts.Pipeline.Wrapper;
using Microsoft.SqlServer.Dts.Pipeline;
using Microsoft.SqlServer.Dts.Runtime;


namespace Pegasus.DtsWrapper
{
    public class ISScriptComponent : ISPipelineComponent
    {
        #region ctor

        /// <summary>
        /// ctor that accepts the parent data flow task, a name for the component
        /// </summary>
        /// <param name="parentDataFlowTask"></param>
        /// <param name="componentname"></param>
        /// <param name="componentDescription"></param>
        public ISScriptComponent(ISDataFlowTask parentDataFlowTask, string componentname) :
            base(parentDataFlowTask, "Microsoft.SqlServer.Dts.Pipeline.ScriptComponentHost, Microsoft.SqlServer.TxScript, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91", componentname)
        {

        }

        /// <summary>
        /// A ctor that accepts a parent data fllow, a name for the component and the previous component (and output) to which this is connected
        /// </summary>
        public ISScriptComponent(ISDataFlowTask parentDataFlowTask, string componentname, ISPipelineComponent sourceComponent, ISOutput sourceOutput, int thisComponentInput = 0) :
            this(parentDataFlowTask, componentname)
        {
            if (sourceOutput != null)
                ConnectToAnotherPipelineComponent(sourceComponent.Name, sourceOutput.Name, thisComponentInput);
            else
                ConnectToAnotherPipelineComponent(sourceComponent.Name, sourceComponent.GetOutputFromIndex(0).Name, thisComponentInput);
        }

        #endregion

        #region Properties

        #region Script Component Type

        /// <summary>
        /// Specify how the script component should be used (Source/Transform/Destination). The options are available in the Pegasus.DtsWrapper.ScriptComponentType enum.
        /// </summary>
        public ScriptComponentType ScriptComponentType
        {
            get
            {
                ScriptComponentType type;
                if (ComponentMetaData.InputCollection.Count > 0 && ComponentMetaData.OutputCollection.Count > 0)
                {
                    type = ScriptComponentType.Transform;
                    _numberOfInputsAllowed = -1;
                    _numberOfOutputsAllowed = -1;
                }
                else if (ComponentMetaData.InputCollection.Count > 0)
                {
                    type = ScriptComponentType.Destination;
                    _numberOfInputsAllowed = 1;
                    _numberOfOutputsAllowed = 0;
                }
                else
                {
                    type = ScriptComponentType.Source;
                    _numberOfInputsAllowed = 0;
                    _numberOfOutputsAllowed = -1;
                }
                return type;
            }
            set
            {
                SetupScriptComponentType(value);
            }
        }

        #endregion

        #region ScriptComponentHost

        /// <summary>
        /// Dts Object used for various script component manipulation
        /// </summary>
        private ScriptComponentHost _scriptComponentHost { get { return (DesignTimeComponent as IDTSManagedComponent100).InnerObject as ScriptComponentHost; } }

        #endregion

        #region ScriptingEngine

        /// <summary>
        /// Dts Object used for various script component manipulation
        /// </summary>
        private VSTAComponentScriptingEngine _currentScriptingEngine
        {
            get
            {
                return _scriptComponentHost.CurrentScriptingEngine;
            }
        }

        #endregion

        #region Source Code

        /// <summary>
        /// The colleciton of source files used in this script component
        /// </summary>
        public string[] SourceCode
        {
            get { return CustomPropertyGetter<string[]>("SourceCode"); }
            set { DesignTimeComponent.SetComponentProperty("SourceCode", value); }
        }

        #endregion

        #region Standard Files To Ignore

        /// <summary>
        /// his is the list of files that are auto-generated by SSIS and should not be manipulated by the end user.
        /// </summary>
        private string[] _ignoreFiles = new string[] { @"Properties\Resources.resx", "BufferWrapper.cs", "ComponentWrapper.cs", "Project", @"Properties\AssemblyInfo.cs", @"Properties\Settings.settings", @"Properties\Resources.Designer.cs" };

        #endregion

        #region ProjectName

        /// <summary>
        /// Name of the Project. The getter is a wrapper around VSTAProjectName
        /// </summary>
        public string ProjectName
        {
            get { return VSTAProjectName; }
            set { AddProject(value); }
        }

        internal string VSTAProjectName
        {
            get { return CustomPropertyGetter<string>("VSTAProjectName"); }
            set { CustomPropertySetter<string>("VSTAProjectName", value); }
        }

        #endregion

        #region ProjectTemplatePath

        /// <summary>
        /// Gets the path of the current template
        /// </summary>
        public string ProjectTemplatePath
        {
            get { return _scriptComponentHost.ProjectTemplatePath; }
        }

        #endregion

        #region ReadOnlyVariables

        /// <summary>
        /// Get/Set the list of read only Variables
        /// </summary>
        public string ReadOnlyVariables
        {
            get { return CustomPropertyGetter<string>("ReadOnlyVariables"); }
            set
            {
                CustomPropertySetter<string>("ReadOnlyVariables", value);
                string[] previousSourceCode = new string[SourceCode.Length];
                for (int i = 0; i < SourceCode.Length; i++)
                {
                    previousSourceCode.SetValue(SourceCode[i], i);
                }
                RebuildProject(null);
            }
        }

        #endregion

        #region ReadWriteVariables

        /// <summary>
        /// Get/Set the list of read write Variables
        /// </summary>
        public string ReadWriteVariables
        {
            get { return CustomPropertyGetter<string>("ReadWriteVariables"); }
            set
            {
                CustomPropertySetter<string>("ReadWriteVariables", value);
                string[] previousSourceCode = new string[SourceCode.Length];
                for (int i = 0; i < SourceCode.Length; i++)
                {
                    previousSourceCode.SetValue(SourceCode[i], i);
                }
                RebuildProject(null);
            }
        }

        #endregion

        #region ScriptLanguage

        /// <summary>
        /// Lanaguage used in the script
        /// </summary>
        public string ScriptLanguage
        {
            get { return CustomPropertyGetter<string>("ScriptLanguage"); }
            //set { CustomPropertySetter<string>("ScriptLanguage", value); }
        }

        #endregion

        #endregion

        #region Methods

        #region Set up Script Component Type
        /// <summary>
        /// Manipulate the Input/Output collection based on the Script Component Type
        /// </summary>
        /// <param name="type"></param>
        private void SetupScriptComponentType(ScriptComponentType type)
        {
            if (type == ScriptComponentType.Source)
            {
                if (ComponentMetaData.InputCollection.Count > 0)
                    ComponentMetaData.InputCollection.RemoveAll();

                foreach (IDTSOutput100 output in ComponentMetaData.OutputCollection)
                {
                    output.SynchronousInputID = 0;
                    output.HasSideEffects = true;
                }
            }
            if (type == ScriptComponentType.Destination)
            {
                if (ComponentMetaData.OutputCollection.Count > 0)
                    ComponentMetaData.OutputCollection.RemoveAll();
            }
        }

        #endregion

        #region Connection

        /// <summary>
        /// Add a connection to the script component.
        /// </summary>
        /// <param name="referenceConnectionName"></param>
        /// <param name="connectionNameInComponent"></param>
        /// <returns></returns>
        internal IDTSRuntimeConnection100 AddConnection_m(string referenceConnectionName, string connectionNameInComponent)
        {

            bool connectionExists = false;
            IDTSRuntimeConnection100 conn = (IDTSRuntimeConnection100)null;
            for (int r = 0; r < ComponentMetaData.RuntimeConnectionCollection.Count; r++)
            {
                if (ComponentMetaData.RuntimeConnectionCollection[r].Name == connectionNameInComponent)
                {
                    connectionExists = true;
                    conn = ComponentMetaData.RuntimeConnectionCollection[r];
                    conn.Name = connectionNameInComponent;
                }
            }

            if (connectionExists == false)
            {
                conn = ComponentMetaData.RuntimeConnectionCollection.New();
                ConnectionManager cmg = GetConnectionManager(referenceConnectionName);
                conn.ConnectionManager = DtsConvert.GetExtendedInterface(cmg);
                conn.ConnectionManagerID = cmg.ID;
                conn.Name = connectionNameInComponent;
            }
            return conn;
        }

        /// <summary>
        /// Add a connection to the script component.
        /// </summary>
        /// <param name="referenceConnectionName"></param>
        /// <param name="connectionNameInComponent"></param>
        /// <returns></returns>
        public void AddConnection(string referenceConnectionName, string connectionNameInComponent)
        {
            AddConnection_m(referenceConnectionName, connectionNameInComponent);
        }

        /// <summary>
        /// Add a connection to the script component
        /// </summary>
        /// <param name="referenceConnection"></param>
        /// <param name="connectionNameInComponent"></param>
        public void AddConnection(ISConnectionManager referenceConnection, string connectionNameInComponent)
        {
            AddConnection_m(referenceConnection.Name, connectionNameInComponent);
        }

        #endregion

        #region Project Manipulation

        #region Add Project

        private void AddProject_m(string projectName)
        {
            _scriptComponentHost.CreateNewProject(projectName, false, true);
            _scriptComponentHost.SaveScriptProject();
        }

        public void AddProject(string projectName)
        {
            bool projectExists = false;
            if (SourceCode.Length > 0)
            {
                projectExists = true;
            }

            if (!(projectExists))
            {
                AddProject_m(projectName);
                VSTAProjectName = projectName;
            }
        }

        #endregion

        #region AddFile

        /// <summary>
        /// adds a file to the project and calls the ScriptComponentHost's SaveScriptProject method
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="content"></param>
        /// <returns></returns>
        private bool AddFile(string fileName, string content)
        {
            _currentScriptingEngine.VstaHelper.AddFileToProject(fileName, content);
            return _scriptComponentHost.SaveScriptProject();
        }

        /// <summary>
        /// Build the Project
        /// </summary>
        /// <param name="buildConfig"></param>
        [Experimental("Not completely tested")]
        public void Build(string buildConfig)
        {
            _currentScriptingEngine.VstaHelper.Build("");
        }

        #endregion

        #region Set Class File

        /// <summary>
        /// Adds/Updates a script file.
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="content"></param>
        public void SetClassFile(string fileName, string content)
        {
            bool fileExists = false;
            foreach (string s in SourceCode)
            {
                if (s == fileName)
                {
                    fileExists = true;
                    break;
                }
            }

            if (fileExists)
            {
                RebuildProject(fileName);
                AddFile(fileName, content);
            }

            if (!(fileExists))
            {
                AddFile(fileName, content);
            }
        }

        #endregion

        #region RebuildProject
        /// <summary>
        /// Rebuild's the project content for all the files except for the standard ignore files and the file passed to this method.
        /// </summary>
        /// <param name="fileToExclude"></param>
        internal void RebuildProject(string fileToExclude)
        {
            string[] previousSourceCode = GetCopyOfSourceCode();
            AddProject_m(ProjectName);
            int iter = 0;
            foreach (string s in previousSourceCode)
            {
                if (iter % 3 == 0)
                {
                    if (s == fileToExclude || s == @"Properties\Resources.resx" || s == "BufferWrapper.cs" || s == "ComponentWrapper.cs" || s.Contains(".csproj") || s == @"Properties\Settings.Designer.cs" || s == "Project" || s == @"Properties\AssemblyInfo.cs" || s == @"Properties\Settings.settings" || s == @"Properties\Resources.Designer.cs")
                    {

                    }
                    else
                    {
                        AddFile(s, previousSourceCode[iter + 2]);
                    }
                }
                iter = iter + 1;
            }
        }

        #endregion

        #region Get File Content
        
        /// <summary>
        /// Get the content in a file
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public string GetFileContent(string fileName)
        {
            int iter = 0;
            string content = "";
            foreach (string s in SourceCode)
            {
                if (s == fileName)
                {
                    content = SourceCode[iter + 2];
                    break;
                }
                iter = iter + 1;
            }
            return content;
        }

        #endregion

        #region Get Previous Source Code

        private string[] GetCopyOfSourceCode()
        {
            string[] previousSourceCode = new string[SourceCode.Length];
            for (int i = 0; i < SourceCode.Length; i++)
            {
                previousSourceCode.SetValue(SourceCode[i], i);
            }
            return previousSourceCode;
        }

        #endregion

        #endregion

        #endregion

    }

    public class ISScriptComponentOutputColumn
    {
        #region Properties

        #region Parent Component

        private ISScriptComponent _parentComponent;

        #endregion

        #region Output

        private IDTSOutput100 _output { get; set; }

        #endregion

        #region OutputColumn

        public ISOutputColumn OutputColumn { get; set; }

        #endregion

        #region Error Row Disposition

        public RowDisposition ErrorRowDisposition
        {
            get { return OutputColumn.ErrorRowDisposition; }
            set { OutputColumn.ErrorRowDisposition = value; }
        }

        #endregion

        #region Truncation Row Disposition

        public RowDisposition TruncationRowDisposition
        {
            get { return OutputColumn.TruncationRowDisposition; }
            set { OutputColumn.TruncationRowDisposition = value; }
        }

        #endregion

        #endregion

        #region ctor

        /// <summary>
        /// Add a Output Column to a script component
        /// </summary>
        /// <param name="parentComponent"></param>
        /// <param name="outputName"></param>
        /// <param name="outputColumnName"></param>
        public ISScriptComponentOutputColumn(ISScriptComponent parentComponent, string outputName, string outputColumnName)
        {
            _parentComponent = parentComponent;
            _output = parentComponent.GetOutputFromName(outputName);
            OutputColumn = new ISOutputColumn(parentComponent, _output.Name, outputColumnName);
            ErrorRowDisposition = RowDisposition.RD_NotUsed;
            TruncationRowDisposition = RowDisposition.RD_NotUsed;
        }

        #endregion

        #region Methods

        public void SetDataTypeProperties(SSISDataType dataType, int length, int precision, int scale, int codePage)
        {
            OutputColumn.SetDataTypeProperties(dataType, length, precision, scale, codePage);
            if (_parentComponent.SourceCode.Length > 0)
            {
                _parentComponent.RebuildProject(null);
            }
        }

        #endregion
    }

    public class ISScriptComponentConnection
    {
        #region ctor
        /// <summary>
        /// Add a connection to the Script Component
        /// </summary>
        /// <param name="parentComponent"></param>
        /// <param name="referenceConnectionName"></param>
        /// <param name="connectionNameInComponent"></param>
        public ISScriptComponentConnection(ISScriptComponent parentComponent, string referenceConnectionName, string connectionNameInComponent)
        {
            _connection = parentComponent.AddConnection_m(referenceConnectionName, connectionNameInComponent);
            if (parentComponent.SourceCode.Length > 0)
                parentComponent.RebuildProject(null);
        }


        public ISScriptComponentConnection(ISScriptComponent parentComponent, ISConnectionManager referenceConnection, string connectionNameInComponent)
        {
            _connection = parentComponent.AddConnection_m(referenceConnection.Name, connectionNameInComponent);
            if (parentComponent.SourceCode.Length > 0)
                parentComponent.RebuildProject(null);
        }

        #endregion

        #region Properties

        private IDTSRuntimeConnection100 _connection;

        public string Name
        {
            get { return _connection.Name; }
            set { _connection.Name = value; }
        }

        public string Description
        {
            get { return _connection.Description; }
            set { _connection.Description = value; }
        }

        #endregion
    }

    public class ISScriptComponentFile
    {
        #region ctor

        /// <summary>
        /// Add or update a Script File
        /// </summary>
        /// <param name="parentScriptComponent"></param>
        /// <param name="fileName"></param>
        /// <param name="content"></param>
        public ISScriptComponentFile(ISScriptComponent parentScriptComponent, string fileName, string content)
        {
            parentScriptComponent.SetClassFile(fileName, content);
        }

        //public TestScriptComponentFile(string parentLineage, string fileName, string content, ISProject ssisProject, ISPackage ssisPackage)
        //    : this(new ISScriptTask(ISContainer.GetContainer(ssisProject, ssisPackage, parentLineage).Container), fileName, content)
        //{

        //}

        #endregion
    }
}
